//! Module registry: an auto-maintained ``<src>/modules/__init__.py``.
//!
//! The registry maps each module name to its import path so AI agents (and the
//! ``fastgen list`` command) can discover the project's module structure at a
//! glance without scanning the filesystem.

use std::fs;
use std::path::Path;

use crate::layout::{registry_path, source_dir_name};
use crate::naming::to_snake;
use crate::writers::{write_file, GeneratedFile, Status};

pub const REGISTRY_HEADER: &str =
    "\"\"\"Module registry - auto-generated by fastgen. Do not edit by hand.\"\"\"";

const MODULES_VAR: &str = "modules";

/// Read the ``modules`` mapping from ``<src>/modules/__init__.py``.
///
/// The registry is plain Python; rather than embedding a Python parser we read
/// the ``modules: dict[str, str] = { ... }`` literal — the format fastgen writes
/// and the README documents as the registry contract.
#[must_use]
pub fn read_registry(project_root: &Path, source: Option<&str>) -> Vec<(String, String)> {
    let path = registry_path(project_root, source);
    match fs::read_to_string(&path) {
        Ok(text) => parse_registry(&text),
        Err(_) => Vec::new(),
    }
}

/// Parse ``"name": "path"`` entries out of the registry literal.
///
/// Returns entries in file order; a repeated key updates its value in place,
/// matching dict-assignment semantics.
fn parse_registry(text: &str) -> Vec<(String, String)> {
    let mut entries: Vec<(String, String)> = Vec::new();
    let mut in_dict = false;
    for line in text.lines() {
        let trimmed = line.trim();
        if !in_dict {
            if is_modules_assignment(trimmed) {
                in_dict = true;
            }
            continue;
        }
        if trimmed.starts_with('}') {
            break;
        }
        if let Some((key, value)) = parse_entry(trimmed) {
            if let Some(existing) = entries.iter_mut().find(|(k, _)| *k == key) {
                existing.1 = value;
            } else {
                entries.push((key, value));
            }
        }
    }
    entries
}

/// True for ``modules = {`` / ``modules: dict[str, str] = {`` and friends.
fn is_modules_assignment(trimmed: &str) -> bool {
    let Some(rest) = trimmed.strip_prefix(MODULES_VAR) else {
        return false;
    };
    let rest = rest.trim_start();
    let after_eq = match rest.strip_prefix(':') {
        // Annotation (e.g. ``dict[str, str]``): skip to the ``=``.
        Some(after_annotation) => match after_annotation.split_once('=') {
            Some((_, after)) => after,
            None => return false,
        },
        None => match rest.strip_prefix('=') {
            Some(after) => after,
            None => return false,
        },
    };
    after_eq.trim_start().starts_with('{')
}

/// Parse one ``"key": "value"`` line, accepting single or double quotes.
fn parse_entry(line: &str) -> Option<(String, String)> {
    let (key, after_key) = next_quoted(line, 0)?;
    let colon = line[after_key..].find(':')? + after_key;
    let (value, _) = next_quoted(line, colon + 1)?;
    Some((key, value))
}

/// Return the next quoted string at/after ``from`` and the index past its closing quote.
fn next_quoted(text: &str, from: usize) -> Option<(String, usize)> {
    let bytes = text.as_bytes();
    let mut i = from;
    while i < bytes.len() {
        let c = bytes[i];
        if c == b'"' || c == b'\'' {
            let quote = c;
            let start = i + 1;
            let mut j = start;
            while j < bytes.len() && bytes[j] != quote {
                j += 1;
            }
            if j >= bytes.len() {
                return None;
            }
            let value = text.get(start..j)?.to_string();
            return Some((value, j + 1));
        }
        i += 1;
    }
    None
}

#[must_use]
pub fn registry_content(modules: &[(String, String)]) -> String {
    let mut sorted: Vec<&(String, String)> = modules.iter().collect();
    sorted.sort_by(|a, b| a.0.cmp(&b.0));
    let body: String = sorted
        .iter()
        .map(|(name, path)| format!("    \"{name}\": \"{path}\","))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "{REGISTRY_HEADER}\n\n{MODULES_VAR}: dict[str, str] = {{\n{body}\n}}\n\n__all__ = [\"{MODULES_VAR}\"]\n"
    )
}

/// Add ``feature`` to the registry and rewrite ``<src>/modules/__init__.py``.
/// # Errors
///
/// Returns an [`io::Error`](std::io::Error) when the registry cannot be read or written.
pub fn register_module(
    project_root: &Path,
    feature: &str,
    source: Option<&str>,
    dry_run: bool,
) -> std::io::Result<GeneratedFile> {
    let source = source.map_or_else(|| source_dir_name(project_root), ToString::to_string);
    let name = to_snake(feature);
    let mut modules = read_registry(project_root, Some(&source));
    let import_path = format!("{source}.modules.{name}");
    if let Some(existing) = modules.iter_mut().find(|(k, _)| *k == name) {
        existing.1 = import_path;
    } else {
        modules.push((name, import_path));
    }
    let content = registry_content(&modules);
    let path = registry_path(project_root, Some(&source));
    if path.exists()
        && fs::read_to_string(&path)?.trim_end_matches('\n') == content.trim_end_matches('\n')
    {
        return Ok(GeneratedFile {
            path,
            content,
            status: Status::Skipped,
        });
    }
    write_file(&path, &content, true, dry_run)
}

/// Return (name, import path, one-line docstring) for every module.
#[must_use]
pub fn list_registered(project_root: &Path, source: Option<&str>) -> Vec<(String, String, String)> {
    let source = source.map_or_else(|| source_dir_name(project_root), ToString::to_string);
    read_registry(project_root, Some(&source))
        .into_iter()
        .map(|(name, import_path)| {
            let doc = module_doc(
                &project_root
                    .join(&source)
                    .join("modules")
                    .join(&name)
                    .join("__init__.py"),
            );
            (name, import_path, doc)
        })
        .collect()
}

/// First line of a module's package docstring, mirroring ``ast.get_docstring``.
fn module_doc(init_file: &Path) -> String {
    let Ok(text) = fs::read_to_string(init_file) else {
        return String::new();
    };
    let trimmed = text.trim_start();
    let Some(rest) = trimmed.strip_prefix("\"\"\"") else {
        return String::new();
    };
    match rest.find("\"\"\"") {
        Some(end) => rest[..end]
            .trim()
            .lines()
            .next()
            .unwrap_or("")
            .trim()
            .to_string(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_generated_registry() {
        let text = registry_content(&[
            ("user".to_string(), "src.modules.user".to_string()),
            ("blog_post".to_string(), "src.modules.blog_post".to_string()),
        ]);
        assert_eq!(
            parse_registry(&text),
            vec![
                ("blog_post".to_string(), "src.modules.blog_post".to_string()),
                ("user".to_string(), "src.modules.user".to_string()),
            ]
        );
    }

    #[test]
    fn parse_unannotated_and_single_quoted_registry() {
        let text = "modules = {\n    'user': 'src.modules.user',\n}\n";
        assert_eq!(
            parse_registry(text),
            vec![("user".to_string(), "src.modules.user".to_string())]
        );
    }

    #[test]
    fn parse_registry_without_dict_is_empty() {
        assert!(parse_registry("MODULES = ['user']\n").is_empty());
        assert!(parse_registry("").is_empty());
    }

    #[test]
    fn parse_repeated_key_updates_in_place() {
        let text = "modules: dict[str, str] = {\n    \"user\": \"a.modules.user\",\n    \"user\": \"b.modules.user\",\n}\n";
        assert_eq!(
            parse_registry(text),
            vec![("user".to_string(), "b.modules.user".to_string())]
        );
    }

    #[test]
    fn module_doc_reads_first_line() {
        let dir = tempfile::tempdir().unwrap();
        let init = dir.path().join("__init__.py");
        std::fs::write(
            &init,
            "\"\"\"User module (vertical slice).\"\"\"\n\nfrom .api.router import router\n",
        )
        .unwrap();
        assert_eq!(module_doc(&init), "User module (vertical slice).");
    }
}
