"""Module registry: an auto-maintained ``app/modules/__init__.py``.

The registry maps each module name to its import path so AI agents (and the
``fastgen list`` command) can discover the project's module structure at a
glance without scanning the filesystem.
"""

from __future__ import annotations

import ast
from pathlib import Path

from ..layout import source_dir_name
from ..naming import to_snake
from ..writers import GeneratedFile, write_file

REGISTRY_HEADER = '"""Module registry - auto-generated by fastgen. Do not edit by hand."""'

_MODULES_VAR = "modules"


def registry_path(project_root: Path, source: str | None = None) -> Path:
    source = source or source_dir_name(project_root)
    return project_root / source / "modules" / "__init__.py"


def read_registry(project_root: Path, source: str | None = None) -> dict[str, str]:
    """Read the ``modules`` mapping from ``<src>/modules/__init__.py``."""
    path = registry_path(project_root, source=source)
    if not path.exists():
        return {}
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign):
            targets = node.targets
        elif isinstance(node, ast.AnnAssign):
            targets = (node.target,) if node.value is not None else ()
        else:
            continue
        if any(isinstance(t, ast.Name) and t.id == _MODULES_VAR for t in targets):
            value = ast.literal_eval(node.value)
            return {name: path for name, path in value.items()}
    return {}


def registry_content(modules: dict[str, str]) -> str:
    body = "\n".join(f'    "{name}": "{path}",' for name, path in sorted(modules.items()))
    return (
        f"{REGISTRY_HEADER}\n\n"
        f"{_MODULES_VAR}: dict[str, str] = {{\n{body}\n}}\n\n"
        '__all__ = ["' + _MODULES_VAR + '"]\n'
    )


def register_module(
    project_root: Path,
    feature: str,
    *,
    source: str | None = None,
    dry_run: bool = False,
) -> GeneratedFile:
    """Add ``feature`` to the registry and rewrite ``<src>/modules/__init__.py``."""
    source = source or source_dir_name(project_root)
    name = to_snake(feature)
    modules = read_registry(project_root, source=source)
    modules[name] = f"{source}.modules.{name}"
    content = registry_content(modules)
    path = registry_path(project_root, source=source)
    if path.exists() and path.read_text(encoding="utf-8").rstrip("\n") == content.rstrip("\n"):
        return GeneratedFile(path=path, content=content, status="skipped")
    return write_file(path, content, force=True, dry_run=dry_run)


def list_registered(project_root: Path, source: str | None = None) -> list[tuple[str, str, str]]:
    """Return (name, import path, one-line docstring) for every module."""
    source = source or source_dir_name(project_root)
    modules = read_registry(project_root, source=source)
    rows: list[tuple[str, str, str]] = []
    for name, import_path in modules.items():
        doc = _module_doc(project_root / source / "modules" / name / "__init__.py")
        rows.append((name, import_path, doc))
    return rows


def _module_doc(init_file: Path) -> str:
    if not init_file.exists():
        return ""
    try:
        tree = ast.parse(init_file.read_text(encoding="utf-8"))
    except SyntaxError:
        return ""
    doc = ast.get_docstring(tree) or ""
    first_line = doc.strip().splitlines()
    return first_line[0] if first_line else ""
